# Configuration for Continuous Integration unit tests
#
# See: https://github.com/Arduino-CI/arduino_ci
#

platforms:
  nano:
    board: arduino:avr:nano
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega328__
        - NUM_SERIAL_PORTS = 1
      warnings:
      flags:
        - -g
        - -O0
        - --coverage
        - -D__TEST__

unittest:
  platforms:
    - nano
