platforms:
  nano:
    board: arduino:avr:nano
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR_ATmega328__
      warnings:
      flags:
        - -coverage

unittest:
  platforms:
    - nano
