name: BetaHazard

on:
  push:
    branches: [ BetaHazard ]
  pull_request:
    branches: [ BetaHazard ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage flake8
        cd src
        pip install -r requirements.txt
        cd ..

    - name: Lint with flake8
      run: |
        cd src
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        cd ..

    - name: Python tests
      run: |
        cd src/node
        ./scripts/build_sil.sh 0
        ./scripts/build_sil.sh 1
        ./scripts/build_sil.sh 4
        cd ..
        coverage run --branch -m unittest discover -v
        cd ..

    - name: Install Arduino CI
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        working-directory: src/node
        bundler-cache: true

    - name: Node tests
      run: |
        cd src/node
        ./run-ci-tests.sh
        cd ../..
      shell: bash

    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        functionalities: gcov

  node-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - "arduino:avr:nano:cpu=atmega328"
          - "STMicroelectronics:stm32:GenF1:pnum=BLUEPILL_F103C8,xserial=generic,usb=none,xusb=FS,opt=osstd,rtlib=nano"
          - "esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,DebugLevel=none"
        include:
          - board: "arduino:avr:nano:cpu=atmega328"
            platform: "arduino:avr"
          - board: "STMicroelectronics:stm32:GenF1:pnum=BLUEPILL_F103C8,xserial=generic,usb=none,xusb=FS,opt=osstd,rtlib=nano"
            platform: "STMicroelectronics:stm32"
            opts: "--additional-urls https://github.com/stm32duino/BoardManagerFiles/raw/master/package_stmicroelectronics_index.json"
          - board: "esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,DebugLevel=none"
            platform: "esp32:esp32"
            opts: "--additional-urls https://dl.espressif.com/dl/package_esp32_index.json"

    steps:
    - uses: actions/checkout@v2
    - uses: arduino/setup-arduino-cli@v1.1.1
    - run: |
        arduino-cli update ${{ matrix.opts }}
        arduino-cli core install ${{ matrix.platform }} ${{ matrix.opts }}
        arduino-cli compile -b ${{ matrix.board }} src/node
  